Replacing custom encryption with SSL
globaldothealth/federation pull request #11
Opened 2023-10-11 23:21 UTC by jim-sheldon

2023-10-12 12:36 UTC, SpencerMarks-IDHA reviewed
please address comments, thanks. also adding Victor to additional eyes on this code. thanks.

2023-10-12 12:36 UTC, SpencerMarks-IDHA commented on e2e/setup_localstack.py
> +		logging.info(f"Created certificate with ARN {certificate_arn}")
this looks like a valid concern.

2023-10-12 12:36 UTC, SpencerMarks-IDHA commented on gh/amqp_server.py
>  	# TODO: If no data log critical and skip
we try 
1) not to have to do comments in code that is going into production 
2) when an exception occurs or a critical error happens, typically just logging (and easily forgetting about it) is a bad idea.

2023-10-12 12:36 UTC, SpencerMarks-IDHA commented on gh/aws.py
> +		logging.debug(f"Certificate: {certificate}")
please check

2023-10-12 12:36 UTC, SpencerMarks-IDHA commented on gh/fake_grpc_service.py
> +            return certificate.get("CertificateArn", "")
returning an empty string is problematic.

2023-10-12 12:41 UTC, SpencerMarks-IDHA commented
Hi, Please give me admin perms on this github account and also please add [victormoyanodiaz] so he can help with code reviews. thanks!

2023-10-12 12:41 UTC, SpencerMarks-IDHA commented
also, please update deps.

2023-10-12 12:49 UTC, jim-sheldon commented on gh/fake_grpc_service.py
> +    logging.info("Getting server credentials")
Sure, can you grant access and I will review?

2023-10-12 13:25 UTC, jim-sheldon commented on gh/amqp_server.py
>  	# TODO: If no data log critical and skip
I like both of those. I updated this block to log `warning` and return. `critical` may be too high.

2023-10-12 13:27 UTC, jim-sheldon commented on gh/fake_grpc_service.py
> +            return certificate.get("CertificateArn", "")
Yeah, I think it's better to `raise` in the event of no cert.

2023-10-12 13:32 UTC, jim-sheldon commented on gh/fake_grpc_service.py
> +    logging.info("Getting server credentials")
Opening another PR for docstrings, will rebase when merged.

2023-10-14 01:12 UTC, jim-sheldon commented on gh/fake_grpc_service.py
> +    logging.info("Getting server credentials")
I added type hints and docstrings.

2023-10-14 01:12 UTC, jim-sheldon commented
> also, please update deps.

All set

2023-10-14 01:16 UTC, jim-sheldon commented
> please address comments, thanks. also adding Victor to additional eyes on this code. thanks.

Thanks for reviewing and providing feedback. I invited him to the repo, and will add him as a reviewer once the invitation gets accepted.

2023-10-16 16:28 UTC, victormoyanodiaz requested changes
Hey Jim! It's really nice to meet you.

It seems like in this PR you are trying to replace the encryption mechanism from a custom encryption mechanism to SSL, but while doing that you also did some additional changes that have nothing to do with that particular goal. 

When working in something specific (and delicate) as changing the encryption mechanism, I'd say you want to keep your PRs as small as possible, with the minimum changes possible. You want to do it like that because if something does not work as expected, it is way easier to find out what's wrong with a PR that only has 8 or 9 files changed, than another one that has 30.

And please, believe me when I say that this thing happens to me every time. I always end up with monster PRs too. But when doing a change like the one you are trying to do, we need to try to keep it small or else it's harder debug issues later on.

On the other hand, I have not run the code and can not tell if it works or not, but the code in general looks good. Happy to approve the pr if we remove the certificate logs

2023-10-16 16:28 UTC, victormoyanodiaz commented on e2e/setup_localstack.py
> +        logging.info(f"Created certificate with ARN {certificate_arn}")
I agree we should not be logging anything related with the certificates. Even though you are not logging the certificate itself here, we should probably not be logging anything related to it

2023-10-16 17:23 UTC, jim-sheldon commented on e2e/setup_localstack.py
> +        logging.info(f"Created certificate with ARN {certificate_arn}")
This script sets up mock AWS resources for local development and testing only.

2023-10-16 17:31 UTC, jim-sheldon commented
> Hey Jim! It's really nice to meet you.
> 
> It seems like in this PR you are trying to replace the encryption mechanism from a custom encryption mechanism to SSL, but while doing that you also did some additional changes that have nothing to do with that particular goal.
> 
> When working in something specific (and delicate) as changing the encryption mechanism, I'd say you want to keep your PRs as small as possible, with the minimum changes possible. You want to do it like that because if something does not work as expected, it is way easier to find out what's wrong with a PR that only has 8 or 9 files changed, than another one that has 30.
> 
> And please, believe me when I say that this thing happens to me every time. I always end up with monster PRs too. But when doing a change like the one you are trying to do, we need to try to keep it small or else it's harder debug issues later on.
> 
> On the other hand, I have not run the code and can not tell if it works or not, but the code in general looks good. Happy to approve the pr if we remove the certificate logs

Hi, nice to meet you too, and thank you for reviewing my PR.

I agree, and apologize this is not a small PR. I too prefer incremental changes and will try to keep things that way. It makes things easier to write and read.

I also want things easily-debuggable, which is why I wrote the code using TDD, focused on integration and end-to-end  tests. In practice, this should let you use Github Actions as a free user in perpetuity, and if I should add tests somewhere, definitely flag it, and I will write and automate them. Local runs work too, you just need a Localstack API key for them, and populated `.env` files.

2023-10-16 18:09 UTC, victormoyanodiaz approved these changes
LGTM

2023-10-16 18:13 UTC, SpencerMarks-IDHA requested changes
Just don't print the certs and we are good here.

2023-10-16 18:27 UTC, jim-sheldon commented
> Just don't print the certs and we are good here.

What remains is diagnostics for mocks used in testing and local development only.

2023-10-16 18:28 UTC, SpencerMarks-IDHA commented
It would be good not have to override the static analysis tools though.

From: Jim ***@***.***>
Date: Monday, October 16, 2023 at 2:27 PM
To: globaldothealth/federation ***@***.***>
Cc: Marks, Spencer ***@***.***>, Review requested ***@***.***>
Subject: Re: [globaldothealth/federation] Replacing custom encryption with SSL (PR #11) [EXTERNAL]
* External Email - Caution *


Just don't print the certs and we are good here.

What remains is diagnostics for mocks used in testing and local development only.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/globaldothealth/federation/pull/11*issuecomment-1765057169__;Iw!!NZvER7FxgEiBAiR_!sCL-iKNTHmBeQsyuYhgvKlFOI9kdENLYz1x7d4cmy2nb87fQPLayu-2ZZMKWw2l3Q7ptf1ymRDxrCHZX6WAeha7VSZmP_OlPSf_WBw$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/APV5E7C4XVMGLKXH3HFQQUTX7V4AVAVCNFSM6AAAAAA54XRIP6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRVGA2TOMJWHE__;!!NZvER7FxgEiBAiR_!sCL-iKNTHmBeQsyuYhgvKlFOI9kdENLYz1x7d4cmy2nb87fQPLayu-2ZZMKWw2l3Q7ptf1ymRDxrCHZX6WAeha7VSZmP_Omy-oLurg$>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2023-10-16 18:35 UTC, jim-sheldon commented
> It would be good not have to override the static analysis tools though.

I will look into how to disable them for certain files to avoid false positives. I changed those log statements for the time being.

2023-10-16 18:40 UTC, SpencerMarks-IDHA approved these changes

2023-10-16 19:01 UTC, merged